# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${END_POINT}:3306/cfsDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: ${PASSWORD}
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      location: /users/charming/temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)

  # spring data jpa 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
  #    org.hibernate.type: trace

  # JWT 속성 설정
jwt:
  issuer: ${USER_KEY}
  secret_key: ${SECRET_KEY}

# AWS S3 설정
cloud:
  aws:
    s3:
      bucket: cfs.video  # s3 버킷 이름
    region:
      static: ap-northeast-2  # region
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}